### ISSUE TITLE
new electron 1.4 with node.js 6.5.0

### ISSUE THREAD

**Issue by mksuper1** [kexplo/electron-edge#19]
Hi.  electron had released a new version 1.4 with node.js 6.5.0. pls update the electron-edge.

thanks

**Comment by kexplo** [comment]
New version updated. you can install from npm

**Comment by mvrk21** [comment]
I am trying to install electron-edge with no luck. I have almost tried everything on the internet. I used node-gyp rebuild, the build was successful but I get the error saying "Module did not self-register". I also used electron-rebuild, even here the build was successful but it gives me the same error. Could anyone please provide me with a tutorial where I can install it on Windows 10. Its working on my Mac but facing issues with Windows 7 and Windows 10.
Operating System : Windows 10
Node Version : 6.5.0
VS Studio : 2015 (all the dependencies are installed)
 Electron Version : 1.4.4
npm version : 4.0.1
Any help would be appreciated.

**Comment by kexplo** [comment]
Thank you for report @harivasista .

New version updated.
See here: https://github.com/kexplo/electron-edge/commit/97d925b797b4b34f34b4d29a7880df7ef57cbbfc 

You can install from npm
