### ISSUE TITLE
electron-edge vs edge

### ISSUE THREAD

**Issue by tmds** [kexplo/electron-edge#2]
Hi,

From the README.md I can't tell what electron-edge does compared to edge. Can you explain what electron-edge includes/excludes compared to edge? And perhaps update the README?

Thanks,

Tom

**Comment by kexplo** [comment]
Hi,

It makes just compatibility between `Electron` and `edge`. ( precompiled binaries for `Electron` )

I will update README.md

Thanks,
Chanwoong

**Comment by tmds** [comment]
What changes are needed to edge to make it compatible with electron?
Is it about compiling edge for the right version of nodejs? Are there other changes needed?

**Comment by kexplo** [comment]
`Electron v0.36.2` use different version of node.js ( v5.1.1 )
You need to install same version of node.js.
And modify `lib/edge.js`, `tools/build.bat`. see https://github.com/kexplo/electron-edge/commit/95394b787074b3a75a1ebdfdfb55f5803d5ac603
- How to know node.js version of Electron : bottom of http://electron.atom.io/
- build.bat means : **The node-gyp Way** section in [using-native-node-modules](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md)

**Comment by tmds** [comment]
Thanks!
