### ISSUE TITLE
Issues installing from NPM

### ISSUE THREAD

**Issue by zacharyshupp** [kexplo/electron-edge#25]
Evening, 

I have been trying all day to get electron-edge installed. I keep receiving an error that a module could not be found. I have tried different version of node.js and electron while receiving the same error message. Is there something required im missing? Below is the error i have received.

```
C:\Users\shuppz\Desktop\electron testing>npm install electron-edge@6.5.2 --save

> edge-cs@1.2.1 install C:\Users\shuppz\Desktop\electron testing\node_modules\edge-cs
> node tools/install.js


> electron-edge@6.5.2 install C:\Users\shuppz\Desktop\electron testing\node_modules\electron-edge
> node tools/install.js

***************************************
Error: The specified module could not be found.
\\?\C:\Users\shuppz\Desktop\electron testing\node_modules\electron-edge\lib\native\win32\x64\6.5.0\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\shuppz\Desktop\electron testing\node_modules\electron-edge\lib\edge.js:49:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
***************************************
Success: platform check for edge.js: node.js x64 v6.4.0
electron-testing@1.0.0 C:\Users\shuppz\Desktop\electron testing
`-- electron-edge@6.5.2
  +-- edge-cs@1.2.1
  `-- nan@2.4.0

npm WARN electron-testing@1.0.0 No description
```

**Comment by whipit** [comment]
I get the same error.  Has anyone looked into this?

**Comment by kexplo** [comment]
Can you tell me your environment( OS, node.js version, electron-version, ... )?

**Comment by whipit** [comment]
Hi - 
My env is 
a) Windows 10(x64).
b) node version 6.9.4
c) electron 1.4.14 (latest from their website)

Also, I saw this SO, that mentions the edge_nativeclr.node module unable to resolve VCRUNTIME140.dll reference.  In my case I do see the dll in my c:\windows\system32 folder.   So I don't think it's the same problem, but not 100% sure.
http://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found/41272553#41272553

**Comment by kexplo** [comment]
I tried to reproduce it in the same environment as you.
* Windows 10 (x64)
* node --version : 6.9.4
* npm list electron : 1.4.14

When I did `npm install electron-edge`, I got the same error .
But there was no problem running.

![image](https://cloud.githubusercontent.com/assets/186918/21986121/777f905e-dc41-11e6-8cad-5a216835cf96.png)

See `.NET Welcomes JavaScript` in cmd.

`electron-edge` contains prebuilt binaries for windows.

I think the install script needs to build new binary or install runtime for prebuilt binaries.
I will try to fix this.

Can you check if there is a problem when you run it?

**Comment by whipit** [comment]
Yes, I do see ".NET Welcomes JavaScript".

I'm a newbie to npm and electron so took me a while to get started.  So I used the electron-quick-start from http://electron.atom.io/, and then updated the main.js file to use the C# code in your README.

Details.

**Install latest Node from https://nodejs.org/en/download/.   (I had an older version 0.12)**

**Install electron-quick-start**
```
# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start

```

**npm install electron-edge**

**Updated the main.js file in electron-quick-start to** 
```
var edge = require('electron-edge');

var helloWorld = edge.func(function () {/*
    async (input) => { 
        return ".NET Welcomes " + input.ToString(); 
    }
*/});

helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
});

```

**Run npm start**

**Comment by whipit** [comment]
BTW - Thanks for being so responsive!  I think this is very cool!

**Comment by kexplo** [comment]
You did it right.
Ignore errors that occur when performing `npm install electron-edge` until I fix it.

**Comment by kexplo** [comment]
Please install a new version of electron-edge (v6.5.4).
Then it will be fixed.

**Comment by whipit** [comment]
It works now without any errors.   Thanks for the quick fix!

```
$ npm install electron-edge

> electron-edge@6.5.4 install C:\electronsandbox\electron-quick-start\node_modules\electron-edge
> node tools/install.js

Success: platform check for edge.js: node.js x64 v6.9.4
electron-quick-start@1.0.0 C:\electronsandbox\electron-quick-start
`-- electron-edge@6.5.4


 /c/electronsandbox/electron-quick-start (master)
$ npm start

> electron-quick-start@1.0.0 start C:\electronsandbox\electron-quick-start
> electron .


.NET Welcomes JavaScript

```
