### ISSUE TITLE
support for electron v0.37.x

### ISSUE THREAD

**Issue by alfrescian** [kexplo/electron-edge#6]
Hi,
is there a roadmap/plan when electron 0.37.x will be supported?
Cheers, jan

**Comment by richardliebmann** [comment]
+1

**Comment by patroza** [comment]
There's also a bump to "Node 5.9.1 merged":https://github.com/atom/electron/commit/4ebd24d1282795b7a1f0549a6769917b934e3368, but I suppose this will end up in 0.38.x :)

**Comment by demogoran** [comment]
Seems I got able to run edge.js for current electron version(0.37.4) under windows using recommendations from https://github.com/kexplo/electron-edge/issues/2.
1. Install node nightly version(not sure, is it required, but I got able to compile edge only with it) from https://nodejs.org/download/nightly/v6.0.0-nightly449684752c449684752c/
2. edge.js files:

lib/edge.js : 

var versionMap = [
    /_[ /^0.8./, '0.8.22' ],
    [ /^0.10./, '0.10.0' ],
    [ /^0.12./, '0.12.0' ],
    [ /^4./, '4.1.1' ],
    [ /^5./, '5.1.0' ],_/
    [ /^6./, '6.0.0-pre' ]
];

tools/build.bat
"%NODEEXE%" "%GYP%" configure build --msvs_version=2013 -%FLAVOR%

->

"%NODEEXE%" "%GYP%" configure build --target=0.37.4 --dist-url=https://atom.io/download/atom-shell --msvs_version=2013 -%FLAVOR%

(not sure, is it required)
1. Build using node-gyp rebuild --target=0.37.4 --arch=x64 --dist-url=https://atom.io/download/atom-shell
2. Create \edge\lib\native\win32\x64\6.0.0-pre folder
3. Copy CoreCLREmbedding.dll, edge_coreclr.node and edge_nativeclr.node from \edge\build\Release to *\6.0.0-pre

After it I got "ATOM_SHELL_ASAR.js:158 Uncaught Error: Module did not self-register.", but my app seems to work correctly.

Sry if there was wrong or overhead steps, I doesn't work with module builds too much.

**Comment by kexplo** [comment]
I'm very busy past weeks.
I will try to update.

**Comment by patroza** [comment]
any news @kexplo ?

Since 0.37.5 they are using 5.10.0 (instead of 6.0.0-pre) btw:

> Fix wrongly using Node v6.0.0-pre, use Node v5.10.0 instead.

**Comment by kexplo** [comment]
@sickboy 
electron-edge updated.
It tested with latest version of [electron-quick-start](https://github.com/electron/electron-quick-start)

Thank you for reminding me

**Comment by alfrescian** [comment]
closing as it was fixed. THX!

**Comment by patroza** [comment]
@kexplo major thanks good sir. appears to work 8-)
