### ISSUE TITLE
Electron 1.1.0 support (Chrome 50, NodeJS 6.1 - VS 2015)

### ISSUE THREAD

**Issue by patroza** [kexplo/electron-edge#8]
https://github.com/electron/electron/releases/tag/v1.1.0

**Comment by patroza** [comment]
I suppose it depends on https://github.com/tjanczuk/edge/issues/425

**Comment by kexplo** [comment]
build.bat updated https://github.com/kexplo/electron-edge/commit/83cc67dc41cc48655ae78a49d8572355f4af7432
prebuilt binary updated https://github.com/kexplo/electron-edge/commit/793c063e0b5f790e352ca51ffe62223be10155b3

Also, you can install from npm

I can't found any problem during build

**Comment by patroza** [comment]
Oh wow, that is awesome @kexplo 
testing!

**Comment by patroza** [comment]
Indeed.. seems to work, gj!
(Did get a compile error, but I suppose it then just switched to the included binaries)

```
***************************************
Error: Das angegebene Modul wurde nicht gefunden.
...\node_modules\electron-edge\lib\native\win32\x64\6.1.0\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\node_modules\electron-edge\lib\edge.js:46:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
***************************************
Success: platform check for edge.js: node.js x64 v6.1.0
```

**Comment by patroza** [comment]
@kexplo I think the following dll's are needed for the Node 6.1 line:
- msvcp140.dll
- vcruntime140.dll

Unsure:
- vccorlib140.dll

(instead of the '120' variants)

**Comment by kexplo** [comment]
@sickboy you're right. It compiled with VS 2015.
I will add 'msvcp140.dll', or send to me pull request :)
thanks for report

**Comment by patroza** [comment]
@kexplo would like to, however things are getting a bit fuzzy now that Electron is statically linked to the VC2015 RT: https://github.com/electron/electron/pull/5602

**Comment by patroza** [comment]
It seems CLR enabled dll's can't be linked statically (https://social.msdn.microsoft.com/Forums/vstudio/en-US/d7223ef0-7878-4c49-b249-642fcf9efd83/mt-and-clr-commandline-options-are-incompatible?forum=vcgeneral),
so for edge one does need to include the dlls, however it runs into some issues for me when used with electron-packager etc; the .node files are extracted to the temp location, but not the runtime dlls.

**Comment by patroza** [comment]
For me the only real solution is to install the actual redists.. My app actually needs 2012, 2013 and now also 2015 :)

https://github.com/sickboy/VCRedistInstaller

**Comment by hannanabdul55** [comment]
@sickboy I also have the same problem when using electron-packager. What is the exact solution which worked? Installing the redists is the only solution? If so, how are you planning to do the same in the shipped product? Here is the error which I get when I package it using electron-packager.   

_The specified module could not be found. C:\blablabla\AppData\Local\Temp\DE7D.tmp.node_

**Comment by patroza** [comment]
@hannanabdul55 I'm using something along the lines of:

```
try {
  let r = cp.spawnSync(path.resolve(path.dirname(process.argv[0]), "resources", "bin", "VCRedistInstaller.exe"), ['VS2012', 'VS2013', 'VS2015']);
  if (r.status != 0 || r.error) throw new Error(`VCRedistInstaller exited with error code: ${r.status}\nOutput: ${r.stdout}\nError: ${r.stderr}\n${r.error}`);
} catch (err) {
  console.warn(err);
  dialog.showErrorBox("Error installing runtime components", "There was a problem trying to install the Visual Studio Runtime components, correct operation is not guaranteed:\n" + err);
}
```
